### ISSUE TITLE
Wheels for Python > 3.8 ?

### ISSUE THREAD

**Issue by neutrinoceros** [radio-astro-tools/casa-formats-io#49]
Would it be possible to publish wheels for more recent versions of Python ?

**Comment by keflavich** [comment]
@astrofrog are we already doing this?

https://github.com/radio-astro-tools/casa-formats-io/blob/b2ee6cd8a77691f33b2fa29514d01a5b1bd42ca2/.github/workflows/publish.yml#L6-L28

**Comment by astrofrog** [comment]
I'll check shortly!

**Comment by neutrinoceros** [comment]
Indeed it looks like your publishing workflow is already set for Python 3.9 and 3.10, so maybe it's just that it hasn't been used since it's last update ?
I checked that there are indeed no wheels available above Python 3.8 at https://pypi.org/simple/casa-formats-io/

**Comment by astrofrog** [comment]
Yes I think that might be it - I was actually thinking we should switch to using the limited Python API so that we can just have one wheel for all Python versions, I could look into this shortly.

**Comment by astrofrog** [comment]
See https://github.com/radio-astro-tools/casa-formats-io/pull/50

**Comment by neutrinoceros** [comment]
Excellent, thank you @astrofrog !

**Comment by astrofrog** [comment]
@astrofrog - could you try and install the latest casa-formats-io 0.2 wheels? They should be compatible with any Python >=3.8 version.

**Comment by neutrinoceros** [comment]
works like a charm, thank you so much ! It's seems to have a very noticeable impact on our build time in yt's CI :-)
